server:
  port: ${PORT:5003} 

logging:
  file:
    path: "logs"
    name: "logs/client.log"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: "logs/client.log"

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER}
        username: ${ADMIN_SECURITY_NAME}
        password: ${ADMIN_SECURITY_PASSWORD}

        instance:
          management-base-url: https://blog-microservice-post.herokuapp.com/
          service-base-url: ${spring.boot.admin.client.instance.management-base-url}
          auto-deregistration: true
          period: 5m
  redis:
    configuration:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    channels:
      channel-tag-add: ${REDIS_CHANNEL_TAG_ADD}
      channel-tag-remove: ${REDIS_CHANNEL_TAG_REMOVE}

  profiles:
    active: "dev"
  application:
    name: blog-microservice-tag
  data:
    mongodb:
      uri: ${MONGODB_URI}
      databaseName: ${MONGODB_DBNAME}
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
springdoc:
  version: '@springdoc.version@'

# security:
#   oauth2:
#     resourceserver:
#       jwt:
#         issuer-uri: ${AUTHORIZATION_SERVER}/auth/realms/blog
#         jwk-set-uri: ${AUTHORIZATION_SERVER}/auth/realms/blog/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3600
    lease-expiration-duration-in-seconds: 3600
    hostname: localhost
  client:
    initial-instance-info-replication-interval-seconds: 3600
    instance-info-replication-interval-seconds: 3600
    registry-fetch-interval-seconds: 3600
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://blog-eureka-server.herokuapp.com/eureka/

discovery:
  uri: https://jjara-discovery.herokuapp.com/v1/discovery/

---
spring:
  profiles: "dev"
  cors:
    allowed-origin: 'http://localhost:3000'
---
spring:
  profiles: "prod"
  cors:
    allowed-origin: >
      https://jonathanjaramorales.herokuapp.com,
      https://blog-eureka-server.herokuapp.com,
      http://jonathanjaramorales.herokuapp.com,
      http://blog-eureka-server.herokuapp.com